### ISSUE TITLE
Simplify LSP codebase in Neovim 0.11

### ISSUE THREAD

**Issue by foxyseta** [visimp/visimp#138]
With the addition of `vim.lsp.config()` and `vim.lsp.enable()` in Neovim 0.11 (https://github.com/neovim/neovim/pull/31031), Can our codebase maybe be somewhat simplified?

**Comment by lucat1** [comment]
Not sure - I don't think this is supposed to replace `nvim-lspconfig`. Lspconfig is a centralized repository with sane defaults for LSP values.

It looks to me like this patch just changes the interface for the setup of LSP servers, but this is for `nvim-lspconfig` to figure out, I don't think we should care.

If I  got this wrong let me know, otherwise we can close this.

**Comment by lucat1** [comment]
Actually, maybe somebody in `nvim-lspconfig` opened a related issue which might explain the impact of this update. Worth taking a look.
